import { AppEnvironment } from '../app/core/config/app-environment';

/** Generated by scripts/generate-docker-environment.mjs — do not edit by hand. */
export const environment: AppEnvironment = {
  production: true,
  apiBaseUrl: "http://localhost:8080/api/v1",
  enableVerboseLogging: false,
};
